#!/usr/bin/env python3
"""Example 08 - GME propagation with a user-supplied memory kernel.

This example intentionally does not estimate a memory kernel.  Instead it
constructs a small synthetic kernel, passes it to the experimental
``run_gme_1d`` workflow,
and compares the resulting non-Markovian transition matrix to the Markovian
reference generated by ``K0`` alone.
"""

from __future__ import annotations

from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import expm

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from stochkin.experimental import memory as memory_kinetics
from stochkin.plotting import _apply_pub_axes
from stochkin.style import publication_style


def main():
    s = np.linspace(-1.5, 1.5, 41)
    F = 0.35 * (s**2 - 1.0) ** 2
    F -= F.min()

    beta = 1.0
    D = 0.01
    memory_times = np.linspace(0.0, 2.0, 201)

    K0 = memory_kinetics.build_smolu_generator_1d(s, F, D=D, beta=beta)
    memory_amplitude = 0.8
    memory_decay_time = 0.70
    memory_rise_time = 0.18
    memory_period = 0.50

    # A deliberately expressive user-supplied kernel: it turns on after a
    # short delay, then decays with damped oscillations.  Because every slice
    # is a scalar multiple of K0, each Sigma(t) still conserves probability.
    memory_envelope = (
        (1.0 - np.exp(-memory_times / memory_rise_time))
        * np.exp(-memory_times / memory_decay_time)
        * (1.0 + 0.65 * np.sin(2.0 * np.pi * memory_times / memory_period))
    )

    # User-provided kernel: shape (n_times, n_states, n_states), units time^-2.
    # Multiplying K0 [time^-1] by memory_amplitude [time^-1] yields Sigma [time^-2].
    Sigma_t = np.asarray(
        [memory_amplitude * envelope * K0 for envelope in memory_envelope],
        dtype=float,
    )

    result = memory_kinetics.run_gme_1d(
        s,
        F,
        D,
        beta=beta,
        Sigma_t=Sigma_t,
        memory_times=memory_times,
        n_steps=200,
        dt=memory_times[1] - memory_times[0],
        enforce_conservation=True,
    )

    T_gme = result["propagation"].trajectory
    times = result["propagation"].times
    T_markov = np.asarray([expm(t * result["K0"]) for t in times])
    memory_norm = np.linalg.norm(result["memory_validation"].Sigma.reshape(len(memory_times), -1), axis=1)

    left_well = s < 0.0
    right_well = s > 0.0
    p_left0 = np.where(left_well, np.exp(-beta * F), 0.0)
    p_left0 /= p_left0.sum()
    p_right_markov = np.asarray([(p_left0 @ T)[right_well].sum() for T in T_markov])
    p_right_gme = np.asarray([(p_left0 @ T)[right_well].sum() for T in T_gme])

    out_path = Path(__file__).with_name("08_user_memory_gme_1d.png")
    with publication_style():
        fig, axes = plt.subplots(1, 3, figsize=(9.6, 2.8))

        axes[0].plot(s, F, "k-", lw=1.5)
        _apply_pub_axes(axes[0], xlabel="s", ylabel="F(s)", title="1D FES")

        axes[1].semilogy(memory_times, memory_norm, "C1-", lw=1.5)
        _apply_pub_axes(
            axes[1],
            xlabel="time",
            ylabel=r"$||\Sigma(t)||_F$",
            title="delayed oscillatory memory",
        )

        axes[2].plot(
            times,
            p_right_markov,
            "k--",
            lw=1.2,
            label=r"Markov $P(L\to R)$",
        )
        axes[2].plot(
            times,
            p_right_gme,
            "C0-",
            lw=1.5,
            label=r"GME $P(L\to R)$",
        )
        _apply_pub_axes(
            axes[2],
            xlabel="time",
            ylabel="right-well probability",
            title="left well to right well",
        )
        axes[2].legend(frameon=False, fontsize=7)

        fig.tight_layout()
        fig.savefig(out_path, dpi=300, bbox_inches="tight")
        plt.close(fig)

    print(f"Saved {out_path}")
    print("GME diagnostics:", result["propagation"].diagnostics)


if __name__ == "__main__":
    main()
